# Dicziunari-Hunspell -- Rhaeto-Romance hunspell dictionary generation
# 
# Copyright (C) 2012-2013 Uli Franke (cls) et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# IMPORTANT NOTICE: All software, content, intellectual property coming
# with this program (usually contained in files) can not be used in any
# way by the Lia Rumantscha (www.liarumantscha.ch/) without explicit
# permission, as they actively block software innovation targeting the
# Rhaeto-Romance language.
#

# http://kb.mozillazine.org/Dictionaries

# Meta/Version
LANG=rm-Puter
VERSION=0.1.0
NAME_EN=Rhaeto-Romance Dictionary (Puter)
DESC_EN=Rhaeto-Romance Dictionary (Puter) 
AUTH_EN=Uli Franke (cls)
NAME_DE=Rätoromanisches Wörterbuch (Puter)
DESC_DE=Rätoromanisches Wörterbuch (Puter) 
AUTH_DE=$(AUTH_EN)

# Resources
PDFWORDLISTDIRS=$(RESDIR)/engadiner-post

include ../Common.mk

